<Project Sdk="Microsoft.NET.Sdk">

  <!-- Targets -->
  <PropertyGroup>
    <TargetFrameworks>net462;net6.0-windows</TargetFrameworks>
    <RootNamespace>TagBites.DB.SqlServer</RootNamespace>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <!-- Build -->
  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <!-- Warnings -->
  <PropertyGroup>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <!-- Package info -->
  <PropertyGroup>
    <Description>SQL Server support for TagBites.DB, built on Microsoft.Data.SqlClient.</Description>
    <PackageTags>database; sqlserver; mssql; sql; data-access</PackageTags>
    <PackageProjectUrl>https://tagbites.com/db/</PackageProjectUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
  </PropertyGroup>

  <!-- References -->
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TagBites.DB\TagBites.DB.csproj" />
  </ItemGroup>

</Project>
