<Project Sdk="Microsoft.NET.Sdk">

  <!-- Targets -->
  <PropertyGroup>
    <TargetFrameworks>net6.0;net462</TargetFrameworks>
    <RootNamespace>TagBites.DB.Sqlite</RootNamespace>
    <Nullable>disable</Nullable>
    <DefineConstants>$(DefineConstants);NUGET</DefineConstants>
  </PropertyGroup>

  <!-- Build -->
  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <!-- Warnings -->
  <PropertyGroup>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <!-- Package info -->
  <PropertyGroup>
    <Description>SQLite support for TagBites.DB, built on System.Data.SQLite.</Description>
    <PackageTags>database; sqlite; sql; data-access; embedded</PackageTags>
    <PackageProjectUrl>https://tagbites.com/db/</PackageProjectUrl>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
  </PropertyGroup>

  <!-- References -->
  <ItemGroup>
    <PackageReference Include="System.Data.SQLite" Version="1.0.119" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TagBites.DB\TagBites.DB.csproj" />
  </ItemGroup>

</Project>
