using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TBS.Data.DB.Schema
{
    public class DbSchemaColumn
    {
        public string Name { get; set; }
        public string DbTypeName { get; set; }
        public int Ordinal { get; set; }
        public string DefaultValue { get; set; }
        public bool IsAutoGenerated { get; set; }
        public bool IsNullable { get; set; }
        public Type Type { get; set; }
    }
}
